// enrollment-keys.ts
// Stores a 6-digit enrollment key per course in localStorage.
// Keys are generated by the super admin and can be regenerated at any time.
// Visible only to super admin (/admin) and teachers (/teacher).

import { COURSES } from "./courses-data";

const STORE_KEY = "buddy_enrollment_keys_v1";

export type EnrollmentKey = {
  courseId: string;
  key: string; // 6-digit string
  updatedAt: string;
};

function hasWindow() {
  return typeof window !== "undefined" && typeof localStorage !== "undefined";
}

function read(): Record<string, EnrollmentKey> {
  if (!hasWindow()) return {};
  try {
    return JSON.parse(localStorage.getItem(STORE_KEY) || "{}");
  } catch {
    return {};
  }
}

function write(store: Record<string, EnrollmentKey>) {
  if (!hasWindow()) return;
  localStorage.setItem(STORE_KEY, JSON.stringify(store));
}

function generate6Digit(): string {
  return String(Math.floor(100000 + Math.random() * 900000));
}

/** Ensure every course has a key, generate any missing ones. */
export function initKeys(): void {
  const store = read();
  let changed = false;
  for (const course of COURSES) {
    if (!store[course.id]) {
      store[course.id] = {
        courseId: course.id,
        key: generate6Digit(),
        updatedAt: new Date().toISOString(),
      };
      changed = true;
    }
  }
  if (changed) write(store);
}

/** Get all enrollment keys (initialises missing ones). */
export function getAllKeys(): EnrollmentKey[] {
  initKeys();
  const store = read();
  return COURSES.map((c) => store[c.id]).filter(Boolean);
}

/** Get a single course's key. */
export function getKey(courseId: string): EnrollmentKey | undefined {
  initKeys();
  return read()[courseId];
}

/** Regenerate the key for a single course. */
export function regenerateKey(courseId: string): EnrollmentKey {
  const store = read();
  const newKey: EnrollmentKey = {
    courseId,
    key: generate6Digit(),
    updatedAt: new Date().toISOString(),
  };
  store[courseId] = newKey;
  write(store);
  return newKey;
}

/** Validate: check if a given code matches the course's enrollment key. */
export function validateEnrollmentKey(courseId: string, input: string): boolean {
  const entry = getKey(courseId);
  return !!entry && entry.key === input.trim();
}
